vpc_cidr_block       = ""
owner                = ""
region               = ""
cluster_name         = ""
private_subnet_block_1 = ""
private_subnet_block_2 = ""
public_subnet_block_1  = ""
public_subnet_block_2  = ""